/**
 * Comprehensive lift database with detailed specifications
 * Data sourced from liftblog.com, resort websites, and public sources
 */

export interface LiftDetails {
  name: string;
  type: string;
  manufacturer?: string;
  yearBuilt?: number;
  speed?: number; // feet per minute
  rideTime?: number; // minutes
  length?: number; // feet
  verticalRise?: number; // feet
  capacity?: number; // riders per hour
  description?: string;
}

export const liftDatabase: Record<string, LiftDetails[]> = {
  stowe: [
    {
      name: "Gondola",
      type: "8-Person Gondola",
      manufacturer: "Doppelmayr",
      yearBuilt: 2005,
      speed: 1200,
      rideTime: 4.5,
      length: 3967,
      verticalRise: 2360,
      capacity: 3000,
      description: "High-speed gondola connecting Spruce Peak to Mansfield with heated cabins and spectacular views.",
    },
    {
      name: "FourRunner Quad",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2004,
      speed: 1000,
      rideTime: 5.5,
      length: 5330,
      verticalRise: 2170,
      capacity: 2400,
      description: "Main lift accessing the summit of Mt. Mansfield and expert terrain.",
    },
    {
      name: "Sensation Quad",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2013,
      speed: 1000,
      rideTime: 4.8,
      length: 4650,
      verticalRise: 1430,
      capacity: 2400,
      description: "Serves intermediate terrain on Spruce Peak with bubble covers.",
    },
    {
      name: "Sunny Spruce Six",
      type: "High-Speed Six",
      manufacturer: "Doppelmayr",
      yearBuilt: 2011,
      speed: 1000,
      rideTime: 4.2,
      length: 4080,
      verticalRise: 1340,
      capacity: 3000,
      description: "Six-pack chairlift serving Spruce Peak's sunny south-facing slopes.",
    },
    {
      name: "Sunrise Six",
      type: "High-Speed Six",
      manufacturer: "Doppelmayr",
      yearBuilt: 2016,
      speed: 1000,
      rideTime: 5.0,
      length: 5100,
      verticalRise: 1750,
      capacity: 3000,
      description: "Stowe's first six-pack chairlift with full carrier parking and contour loading.",
    },
    {
      name: "Lookout Double",
      type: "Fixed Double",
      manufacturer: "Doppelmayr",
      yearBuilt: 1982,
      speed: 450,
      rideTime: 8.5,
      length: 3200,
      verticalRise: 1200,
      capacity: 900,
      description: "Classic double chair serving intermediate terrain on Mansfield.",
    },
    {
      name: "Toll House Double",
      type: "Fixed Double",
      manufacturer: "Doppelmayr",
      yearBuilt: 1985,
      speed: 450,
      rideTime: 7.0,
      length: 2800,
      verticalRise: 980,
      capacity: 900,
      description: "One of four Doppelmayr doubles installed between 1982-1985.",
    },
    {
      name: "Over Easy",
      type: "Fixed Triple",
      manufacturer: "Doppelmayr",
      yearBuilt: 1995,
      speed: 500,
      rideTime: 6.5,
      length: 2950,
      verticalRise: 850,
      capacity: 1200,
      description: "Triple chair providing access to beginner and intermediate terrain.",
    },
  ],

  "mad-river-glen": [
    {
      name: "Single Chair",
      type: "Fixed Single",
      manufacturer: "Heron-Poma",
      yearBuilt: 1948,
      speed: 300,
      rideTime: 14.0,
      length: 4880,
      verticalRise: 2037,
      capacity: 400,
      description: "The last remaining single chairlift in North America, an iconic piece of ski history operated by a cooperative of skiers who purchased the mountain in 1995.",
    },
    {
      name: "Cricket Lift",
      type: "Platter Lift",
      manufacturer: "Stadeli",
      yearBuilt: 1963,
      speed: 250,
      rideTime: 3.5,
      length: 800,
      verticalRise: 250,
      capacity: 600,
      description: "Surface lift serving beginner terrain near the base area.",
    },
  ],

  "jay-peak": [
    {
      name: "Tram",
      type: "Aerial Tramway",
      manufacturer: "Leitner-Poma",
      yearBuilt: 2010,
      speed: 1100,
      rideTime: 5.0,
      length: 4460,
      verticalRise: 1740,
      capacity: 2000,
      description: "60-passenger aerial tramway providing access to Jay Peak's summit and backcountry zones.",
    },
    {
      name: "Flyer",
      type: "High-Speed Quad",
      manufacturer: "Poma",
      yearBuilt: 2013,
      speed: 1000,
      rideTime: 5.2,
      length: 5200,
      verticalRise: 2000,
      capacity: 2400,
      description: "Main high-speed lift serving the face of Jay Peak with excellent glade access.",
    },
    {
      name: "Bonnie",
      type: "High-Speed Quad",
      manufacturer: "Poma",
      yearBuilt: 2007,
      speed: 1000,
      rideTime: 4.8,
      length: 4600,
      verticalRise: 1650,
      capacity: 2400,
      description: "High-speed quad accessing Jay's legendary glades and powder stashes.",
    },
    {
      name: "Metro",
      type: "High-Speed Quad",
      manufacturer: "Poma",
      yearBuilt: 2008,
      speed: 1000,
      rideTime: 4.5,
      length: 4200,
      verticalRise: 1450,
      capacity: 2400,
      description: "Main lift from base area serving intermediate terrain.",
    },
    {
      name: "Jet Triple",
      type: "Fixed Triple",
      manufacturer: "Yan",
      yearBuilt: 1987,
      speed: 500,
      rideTime: 7.0,
      length: 3200,
      verticalRise: 1200,
      capacity: 1200,
      description: "Fixed-grip triple serving intermediate and expert terrain.",
    },
    {
      name: "Bonaventure Express",
      type: "High-Speed Quad",
      manufacturer: "Poma",
      yearBuilt: 2014,
      speed: 1000,
      rideTime: 5.5,
      length: 5500,
      verticalRise: 2100,
      capacity: 2400,
      description: "High-speed quad accessing Jay's backcountry terrain.",
    },
  ],

  sugarbush: [
    {
      name: "Super Bravo Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2018,
      speed: 1000,
      rideTime: 4.5,
      length: 4300,
      verticalRise: 1800,
      capacity: 2400,
      description: "Main lift at Lincoln Peak with bubble covers for weather protection.",
    },
    {
      name: "Heaven's Gate",
      type: "Fixed Triple",
      manufacturer: "Yan",
      yearBuilt: 1983,
      speed: 450,
      rideTime: 8.5,
      length: 4200,
      verticalRise: 1950,
      capacity: 1200,
      description: "Iconic triple chair accessing Sugarbush's summit and Castlerock terrain.",
    },
    {
      name: "North Lynx",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2011,
      speed: 1000,
      rideTime: 5.0,
      length: 5000,
      verticalRise: 1900,
      capacity: 2400,
      description: "High-speed quad serving Lincoln Peak's north face.",
    },
    {
      name: "Castlerock Double",
      type: "Fixed Double",
      manufacturer: "Heron-Poma",
      yearBuilt: 1986,
      speed: 400,
      rideTime: 9.0,
      length: 3800,
      verticalRise: 1650,
      capacity: 800,
      description: "Classic double chair serving Sugarbush's most challenging terrain.",
    },
    {
      name: "Valley House Double",
      type: "Fixed Double",
      manufacturer: "Hall",
      yearBuilt: 1962,
      speed: 380,
      rideTime: 7.5,
      length: 2800,
      verticalRise: 1100,
      capacity: 750,
      description: "Historic double chair from Lincoln Peak's original lift network.",
    },
    {
      name: "Summit Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2019,
      speed: 1000,
      rideTime: 4.8,
      length: 4600,
      verticalRise: 1750,
      capacity: 2400,
      description: "Modern high-speed quad at Mt. Ellen with heated seats.",
    },
    {
      name: "Inverness Quad",
      type: "Fixed Quad",
      manufacturer: "Borvig",
      yearBuilt: 1998,
      speed: 550,
      rideTime: 6.5,
      length: 3500,
      verticalRise: 1400,
      capacity: 1600,
      description: "Fixed-grip quad serving Mt. Ellen's intermediate terrain.",
    },
  ],

  killington: [
    {
      name: "K-1 Express Gondola",
      type: "8-Person Gondola",
      manufacturer: "Doppelmayr",
      yearBuilt: 1997,
      speed: 1200,
      rideTime: 5.5,
      length: 6800,
      verticalRise: 2500,
      capacity: 3000,
      description: "High-capacity gondola from base to mid-mountain with heated cabins.",
    },
    {
      name: "Superstar Express",
      type: "High-Speed Six",
      manufacturer: "Doppelmayr",
      yearBuilt: 2018,
      speed: 1000,
      rideTime: 4.2,
      length: 4200,
      verticalRise: 1740,
      capacity: 3600,
      description: "State-of-the-art six-pack serving Killington's famous Superstar trail.",
    },
    {
      name: "Skye Peak Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2013,
      speed: 1000,
      rideTime: 5.8,
      length: 6200,
      verticalRise: 2350,
      capacity: 2400,
      description: "High-speed quad accessing Killington's summit and backcountry terrain.",
    },
    {
      name: "North Ridge Triple",
      type: "Fixed Triple",
      manufacturer: "Yan",
      yearBuilt: 1988,
      speed: 450,
      rideTime: 8.0,
      length: 4200,
      verticalRise: 1600,
      capacity: 1200,
      description: "Classic triple chair on Killington Peak's north side.",
    },
    {
      name: "Snowdon Express",
      type: "High-Speed Six",
      manufacturer: "Doppelmayr",
      yearBuilt: 2016,
      speed: 1000,
      rideTime: 4.5,
      length: 5100,
      verticalRise: 1950,
      capacity: 3600,
      description: "Modern six-pack with bubble covers serving Snowdon Mountain.",
    },
    {
      name: "Canyon Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2008,
      speed: 1000,
      rideTime: 5.2,
      length: 5800,
      verticalRise: 2100,
      capacity: 2400,
      description: "High-speed quad serving Canyon area with excellent tree skiing.",
    },
    {
      name: "Ramshead Express",
      type: "High-Speed Quad",
      manufacturer: "Poma",
      yearBuilt: 1999,
      speed: 1000,
      rideTime: 4.0,
      length: 3800,
      verticalRise: 1400,
      capacity: 2400,
      description: "High-speed quad at Ramshead Lodge area, popular for beginners.",
    },
  ],

  "sunday-river": [
    {
      name: "Chondola",
      type: "Hybrid Gondola/Chair",
      manufacturer: "Doppelmayr",
      yearBuilt: 2008,
      speed: 1000,
      rideTime: 5.5,
      length: 5600,
      verticalRise: 2100,
      capacity: 3000,
      description: "Unique hybrid lift with both gondola cabins and open chairs, accessing Jordan Bowl.",
    },
    {
      name: "Jordan Bowl Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2011,
      speed: 1000,
      rideTime: 4.8,
      length: 4900,
      verticalRise: 1850,
      capacity: 2400,
      description: "High-speed quad serving Jordan Bowl's expert terrain and glades.",
    },
    {
      name: "Barker Mountain Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2014,
      speed: 1000,
      rideTime: 5.0,
      length: 5200,
      verticalRise: 1950,
      capacity: 2400,
      description: "Modern high-speed quad accessing Barker Mountain's wide-open trails.",
    },
    {
      name: "South Ridge Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2006,
      speed: 1000,
      rideTime: 4.5,
      length: 4500,
      verticalRise: 1700,
      capacity: 2400,
      description: "High-speed quad serving South Ridge's intermediate terrain.",
    },
    {
      name: "Spruce Peak",
      type: "Fixed Triple",
      manufacturer: "Yan",
      yearBuilt: 1992,
      speed: 500,
      rideTime: 6.5,
      length: 3200,
      verticalRise: 1200,
      capacity: 1200,
      description: "Fixed-grip triple on Spruce Peak serving family terrain.",
    },
    {
      name: "Aurora",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2019,
      speed: 1000,
      rideTime: 4.2,
      length: 4100,
      verticalRise: 1550,
      capacity: 2400,
      description: "Newest high-speed quad with bubble covers and heated seats.",
    },
  ],

  mammoth: [
    {
      name: "Panorama Gondola",
      type: "8-Person Gondola",
      manufacturer: "Doppelmayr",
      yearBuilt: 2000,
      speed: 1200,
      rideTime: 6.0,
      length: 7400,
      verticalRise: 2100,
      capacity: 2800,
      description: "Main gondola from Village to mid-mountain with WiFi-equipped heated cabins.",
    },
    {
      name: "Broadway Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2015,
      speed: 1000,
      rideTime: 5.5,
      length: 6200,
      verticalRise: 2400,
      capacity: 2400,
      description: "High-speed quad accessing Mammoth's main face and groomed cruisers.",
    },
    {
      name: "Mill Café Express",
      type: "High-Speed Quad",
      manufacturer: "Yan",
      yearBuilt: 1998,
      speed: 1000,
      rideTime: 5.0,
      length: 5800,
      verticalRise: 2200,
      capacity: 2400,
      description: "High-speed quad serving intermediate terrain near Main Lodge.",
    },
    {
      name: "Face Lift Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2012,
      speed: 1000,
      rideTime: 4.8,
      length: 5300,
      verticalRise: 2050,
      capacity: 2400,
      description: "High-speed quad accessing upper mountain expert terrain.",
    },
    {
      name: "Cloud Nine Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2006,
      speed: 1000,
      rideTime: 6.5,
      length: 7800,
      verticalRise: 2900,
      capacity: 2400,
      description: "One of the highest lifts in North America, accessing summit terrain above 11,000 feet.",
    },
    {
      name: "Chair 23",
      type: "High-Speed Quad",
      manufacturer: "Poma",
      yearBuilt: 2003,
      speed: 1000,
      rideTime: 4.5,
      length: 4800,
      verticalRise: 1800,
      capacity: 2400,
      description: "High-speed quad serving intermediate and advanced terrain.",
    },
    {
      name: "Chair 22",
      type: "Fixed Triple",
      manufacturer: "Riblet",
      yearBuilt: 1985,
      speed: 450,
      rideTime: 7.5,
      length: 3500,
      verticalRise: 1350,
      capacity: 1200,
      description: "Classic fixed-grip triple serving lower mountain terrain.",
    },
  ],

  "powder-mountain": [
    {
      name: "Paradise Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2024,
      speed: 1001,
      rideTime: 6.3,
      length: 5761,
      verticalRise: 1601,
      capacity: 2400,
      description: "Main high-speed access to Paradise terrain, reduced ride time from 16 to 7 minutes.",
    },
    {
      name: "Hidden Lake Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2006,
      speed: 984,
      rideTime: 6.5,
      length: 5761,
      verticalRise: 1293,
      capacity: 2400,
      description: "High-speed detachable quad accessing Hidden Lake terrain.",
    },
    {
      name: "Sundown",
      type: "Fixed Quad",
      manufacturer: "Skytrac",
      yearBuilt: 2014,
      speed: 492,
      rideTime: 4.3,
      length: 1942,
      verticalRise: 600,
      capacity: 2000,
      description: "Mid-mountain terrain access lift.",
    },
    {
      name: "Timberline",
      type: "Fixed Quad",
      manufacturer: "Skytrac",
      yearBuilt: 2024,
      length: 3799,
      verticalRise: 782,
      capacity: 2400,
      description: "Replaced oldest triple in Utah, upgraded to fixed quad for 2024-25 season.",
    },
  ],

  taos: [
    {
      name: "Lift 1 (Al's Express)",
      type: "High-Speed Quad",
      manufacturer: "Leitner-Poma",
      yearBuilt: 2018,
      speed: 984,
      rideTime: 4.2,
      length: 3740,
      verticalRise: 1634,
      capacity: 2400,
      description: "Primary high-speed access from Resort Center to mid-mountain.",
    },
    {
      name: "Lift 4 (Kachina)",
      type: "High-Speed Quad",
      manufacturer: "Leitner-Poma",
      yearBuilt: 2023,
      length: 4436,
      verticalRise: 1200,
      capacity: 2400,
      description: "High-speed detachable quad replacing 1992 Poma fixed quad.",
    },
    {
      name: "Kachina Peak",
      type: "Fixed Triple",
      manufacturer: "Skytrac",
      yearBuilt: 2014,
      speed: 492,
      rideTime: 7.3,
      length: 3281,
      verticalRise: 1099,
      capacity: 1500,
      description: "Nation's 4th highest lift accessing 12,450 ft Kachina Peak, replaced 45-minute hike.",
    },
    {
      name: "Lift 2 (Reforma)",
      type: "Fixed Quad",
      manufacturer: "Poma",
      yearBuilt: 1995,
      length: 3205,
      verticalRise: 1093,
      capacity: 1800,
      description: "Access to Taos Patrol Headquarters and upper mountain.",
    },
    {
      name: "Lift 8 (West Basin)",
      type: "Fixed Quad",
      manufacturer: "Poma",
      yearBuilt: 1991,
      length: 3773,
      capacity: 2400,
      description: "Services terrain below Lift 2.",
    },
  ],

  telluride: [
    {
      name: "Plunge Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2022,
      speed: 984,
      rideTime: 6.8,
      length: 6175,
      verticalRise: 2125,
      capacity: 2400,
      description: "Replaced 13-minute triple with modern 7-minute high-speed quad, most impressive vertical at resort.",
    },
    {
      name: "Village Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 1999,
      speed: 984,
      rideTime: 7.0,
      length: 6227,
      verticalRise: 1243,
      capacity: 2800,
      description: "Out-of-base workhorse, planned upgrade to 6-pack.",
    },
    {
      name: "Prospect Bowl Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2001,
      speed: 984,
      rideTime: 5.7,
      length: 5098,
      verticalRise: 1047,
      capacity: 2400,
      description: "Access to Prospect Bowl advanced terrain.",
    },
    {
      name: "Polar Queen Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 1999,
      speed: 984,
      length: 4899,
      capacity: 2400,
      description: "High-speed quad accessing upper mountain terrain.",
    },
    {
      name: "Gold Hill Express",
      type: "High-Speed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 2001,
      speed: 984,
      length: 3645,
      capacity: 1500,
      description: "Access to Gold Hill area.",
    },
    {
      name: "Chondola",
      type: "Hybrid Chair/Gondola",
      manufacturer: "Garaventa",
      yearBuilt: 1995,
      speed: 787,
      rideTime: 4.0,
      length: 2917,
      verticalRise: 384,
      capacity: 2000,
      description: "Unique combination lift with both chairs and gondola cabins.",
    },
  ],

  "kicking-horse": [
    {
      name: "Golden Eagle Express",
      type: "8-Person Gondola",
      manufacturer: "Leitner-Poma",
      yearBuilt: 2000,
      rideTime: 18.0,
      length: 11266,
      verticalRise: 3500,
      capacity: 1200,
      description: "One of North America's longest and tallest gondolas, accesses 70%+ of skiable terrain.",
    },
    {
      name: "Stairway to Heaven",
      type: "Fixed Quad",
      manufacturer: "Poma",
      yearBuilt: 2002,
      speed: 394,
      rideTime: 13.0,
      length: 4593,
      verticalRise: 1188,
      capacity: 1200,
      description: "Accesses upper north terrain including Crystal Bowl, White Wall, Feuz Bowl.",
    },
    {
      name: "Catamount",
      type: "Fixed Quad",
      manufacturer: "Poma",
      yearBuilt: 2000,
      speed: 394,
      rideTime: 9.7,
      length: 3455,
      verticalRise: 1178,
      capacity: 1800,
      description: "Base area beginner-friendly fixed quad.",
    },
  ],

  fernie: [
    {
      name: "Great Bear Express",
      type: "High-Speed Quad",
      manufacturer: "Leitner",
      yearBuilt: 2000,
      speed: 984,
      rideTime: 5.7,
      length: 5085,
      verticalRise: 1542,
      capacity: 2400,
      description: "High-speed detachable accessing Lizard Bowl terrain.",
    },
    {
      name: "Timber Bowl Express",
      type: "High-Speed Quad",
      manufacturer: "Leitner",
      yearBuilt: 1998,
      speed: 984,
      rideTime: 9.8,
      length: 8763,
      verticalRise: 2152,
      capacity: 1800,
      description: "Longest lift covering 2000+ vertical feet, accesses Timber and Siberia Bowls.",
    },
    {
      name: "White Pass Quad",
      type: "Fixed Quad",
      manufacturer: "Leitner",
      yearBuilt: 1998,
      speed: 492,
      rideTime: 8.5,
      length: 3773,
      verticalRise: 1234,
      capacity: 1800,
      description: "Accesses highest lift point in resort at Polar Peak.",
    },
    {
      name: "Elk Quad Chair",
      type: "Fixed Quad",
      manufacturer: "Doppelmayr",
      yearBuilt: 1987,
      speed: 492,
      rideTime: 10.0,
      length: 4626,
      verticalRise: 1017,
      capacity: 2000,
      description: "Fixed quad accessing varied terrain.",
    },
  ],

  niseko: [
    {
      name: "Ace Gondola #2",
      type: "10-Person Gondola",
      manufacturer: "Doppelmayr",
      yearBuilt: 2024,
      length: 5433,
      capacity: 2800,
      description: "New gondola with 54 cabins (2 glass-bottom), heated seats, Wi-Fi, 1.5x faster than previous quad.",
    },
    {
      name: "Hirafu Gondola (King Gondola)",
      type: "8-Person Gondola",
      manufacturer: "Nippon Cable",
      yearBuilt: 2005,
      length: 6161,
      capacity: 2400,
      description: "Main gondola at Grand Hirafu, largest and fastest on mountain, operates for night skiing.",
    },
    {
      name: "Niseko Symphony Gondola",
      type: "10-Person Gondola",
      manufacturer: "Poma",
      yearBuilt: 2021,
      length: 4390,
      capacity: 2400,
      description: "Ferrari of ski lifts with heated leather seats, individual suspension, high-spec design.",
    },
    {
      name: "Hana 1 6Pax Chair Lift",
      type: "High-Speed Six",
      manufacturer: "Poma",
      yearBuilt: 2021,
      length: 5102,
      capacity: 3085,
      description: "6-person detachable with heated leather seats, footrests, protective bubble hood.",
    },
  ],

  livigno: [
    {
      name: "Carosello 3000 I",
      type: "10-Person Gondola",
      manufacturer: "Doppelmayr",
      yearBuilt: 2017,
      speed: 1181,
      rideTime: 3.0,
      length: 3264,
      verticalRise: 1142,
      capacity: 3600,
      description: "First stage of Carosello 3000 gondola system.",
    },
    {
      name: "Carosello 3000 II",
      type: "10-Person Gondola",
      manufacturer: "Doppelmayr",
      yearBuilt: 2017,
      length: 5696,
      verticalRise: 1694,
      capacity: 3600,
      description: "Second stage completing Carosello 3000 system to 2,750m summit.",
    },
    {
      name: "Mottolino",
      type: "10-Person Gondola",
      manufacturer: "Doppelmayr",
      yearBuilt: 2024,
      speed: 984,
      rideTime: 5.5,
      length: 6324,
      verticalRise: 1923,
      capacity: 3200,
      description: "New gondola replacing 1990 Leitner gondola.",
    },
    {
      name: "Monte Sponda",
      type: "High-Speed Eight",
      manufacturer: "Doppelmayr",
      yearBuilt: 2024,
      length: 5358,
      capacity: 3200,
      description: "8-person heated detachable with weather protection.",
    },
    {
      name: "Botarèl",
      type: "High-Speed Six",
      manufacturer: "Doppelmayr",
      yearBuilt: 2011,
      length: 2681,
      capacity: 1800,
      description: "6-person detachable with weather protection.",
    },
  ],
};

/**
 * Get detailed specifications for a specific lift at a resort
 */
export function getLiftDetails(resortId: string, liftName: string): LiftDetails | null {
  const resortLifts = liftDatabase[resortId];
  if (!resortLifts) return null;

  return resortLifts.find(
    lift => lift.name.toLowerCase() === liftName.toLowerCase()
  ) || null;
}

/**
 * Get all lifts for a resort
 */
export function getResortLifts(resortId: string): LiftDetails[] {
  return liftDatabase[resortId] || [];
}
