import { Resort } from "@/types";

export const RESORTS: Resort[] = [
  {
    id: "stowe",
    name: "Stowe Mountain Resort",
    state: "Vermont",
    country: "USA",
    region: "Northeast USA",
    latitude: 44.5305,
    longitude: -72.7817,
    elevations: {
      base: 1600,
      mid: 2750,
      summit: 3625,
    },
    passes: ["Epic"],
    season: {
      openingDay: "2024-11-23",
      closingDay: "2025-04-20",
      typicalOpening: "11-20",
      typicalClosing: "04-20",
    },
    lifts: [
      { name: "Gondola", type: "Gondola", bottomElevation: 1600, topElevation: 3625, windExposure: "Moderate" },
      { name: "Fourrunner Quad", type: "High-Speed Quad", bottomElevation: 1600, topElevation: 2360, windExposure: "Low" },
      { name: "Sensation Quad", type: "High-Speed Quad", bottomElevation: 2360, topElevation: 2900, windExposure: "Moderate" },
      { name: "Sunny Spruce Quad", type: "Fixed Quad", bottomElevation: 1600, topElevation: 2100, windExposure: "Low" },
      { name: "Mansfield Triple", type: "Triple", bottomElevation: 2900, topElevation: 3625, windExposure: "High" },
      { name: "Chin Clip Quad", type: "High-Speed Quad", bottomElevation: 2900, topElevation: 3625, windExposure: "High" },
      { name: "Lookout Double", type: "Double", bottomElevation: 2100, topElevation: 2600, windExposure: "Moderate" },
      { name: "Perry Merrill Double", type: "Double", bottomElevation: 1600, topElevation: 2100, windExposure: "Low" },
    ],
  },
  {
    id: "mad-river-glen",
    name: "Mad River Glen",
    state: "Vermont",
    country: "USA",
    region: "Northeast USA",
    latitude: 44.2011,
    longitude: -72.9211,
    elevations: {
      base: 1600,
      mid: 2550,
      summit: 3637,
    },
    passes: ["Independent"],
    season: {
      openingDay: "2024-12-14",
      closingDay: "2025-04-06",
      typicalOpening: "12-15",
      typicalClosing: "04-07",
    },
    blogUrl: "http://madriverglenweather.blogspot.com/",
  },
  {
    id: "jay-peak",
    name: "Jay Peak Resort",
    state: "Vermont",
    country: "USA",
    region: "Northeast USA",
    latitude: 44.9364,
    longitude: -72.5031,
    elevations: {
      base: 1815,
      mid: 2815,
      summit: 3968,
    },
    passes: ["Indy", "Independent"],
    season: {
      openingDay: "2024-11-29",
      closingDay: "2025-04-27",
      typicalOpening: "11-25",
      typicalClosing: "04-27",
    },
  },
  {
    id: "sugarbush",
    name: "Sugarbush Resort",
    state: "Vermont",
    country: "USA",
    region: "Northeast USA",
    latitude: 44.1347,
    longitude: -72.9028,
    elevations: {
      base: 1535,
      mid: 2700,
      summit: 4083,
    },
    passes: ["Ikon"],
    season: {
      openingDay: "2024-11-30",
      closingDay: "2025-04-20",
      typicalOpening: "11-25",
      typicalClosing: "04-20",
    },
  },
  {
    id: "magic-mountain",
    name: "Magic Mountain",
    state: "Vermont",
    country: "USA",
    region: "Northeast USA",
    latitude: 43.2,
    longitude: -72.77,
    elevations: {
      base: 1350,
      mid: 2100,
      summit: 2850,
    },
    passes: ["Indy", "Independent"],
    season: {
      openingDay: "2024-12-21",
      closingDay: "2025-04-06",
      typicalOpening: "12-20",
      typicalClosing: "04-07",
    },
  },
  {
    id: "killington",
    name: "Killington Resort",
    state: "Vermont",
    country: "USA",
    region: "Northeast USA",
    latitude: 43.6045,
    longitude: -72.8203,
    elevations: {
      base: 1165,
      mid: 2700,
      summit: 4241,
    },
    passes: ["Ikon", "Independent"],
    season: {
      openingDay: "2024-10-20",
      closingDay: "2025-05-25",
      typicalOpening: "10-20",
      typicalClosing: "05-25",
    },
  },
  {
    id: "sunday-river",
    name: "Sunday River",
    state: "Maine",
    country: "USA",
    region: "Northeast USA",
    latitude: 44.4728,
    longitude: -70.8561,
    elevations: {
      base: 800,
      mid: 2100,
      summit: 3140,
    },
    passes: ["Ikon", "Independent"],
    season: {
      openingDay: "2024-11-29",
      closingDay: "2025-04-27",
      typicalOpening: "11-25",
      typicalClosing: "04-27",
    },
  },
  {
    id: "sugarloaf",
    name: "Sugarloaf",
    state: "Maine",
    country: "USA",
    region: "Northeast USA",
    latitude: 45.0317,
    longitude: -70.3133,
    elevations: {
      base: 1417,
      mid: 2825,
      summit: 4237,
    },
    passes: ["Ikon", "Independent"],
    season: {
      openingDay: "2024-11-29",
      closingDay: "2025-05-04",
      typicalOpening: "11-25",
      typicalClosing: "05-01",
    },
  },
  {
    id: "mammoth",
    name: "Mammoth Mountain",
    state: "California",
    country: "USA",
    region: "Western USA",
    latitude: 37.6308,
    longitude: -119.0326,
    elevations: {
      base: 7953,
      mid: 9500,
      summit: 11053,
    },
    passes: ["Ikon"],
    season: {
      openingDay: "2024-11-14",
      closingDay: "2025-05-26",
      typicalOpening: "11-10",
      typicalClosing: "05-31",
    },
  },
  {
    id: "powder-mountain",
    name: "Powder Mountain",
    state: "Utah",
    country: "USA",
    region: "Western USA",
    latitude: 41.3803,
    longitude: -111.7797,
    elevations: {
      base: 6895,
      mid: 8200,
      summit: 8464,
    },
    passes: ["Ikon"],
  },
  {
    id: "taos",
    name: "Taos Ski Valley",
    state: "New Mexico",
    country: "USA",
    region: "Western USA",
    latitude: 36.5972,
    longitude: -105.4461,
    elevations: {
      base: 9207,
      mid: 10800,
      summit: 12481,
    },
    passes: ["Ikon"],
  },
  {
    id: "telluride",
    name: "Telluride Ski Resort",
    state: "Colorado",
    country: "USA",
    region: "Western USA",
    latitude: 37.9375,
    longitude: -107.8123,
    elevations: {
      base: 8725,
      mid: 10900,
      summit: 12570,
    },
    passes: ["Epic"],
  },
  {
    id: "kicking-horse",
    name: "Kicking Horse Mountain Resort",
    state: "British Columbia",
    country: "Canada",
    region: "Canada",
    latitude: 51.2989,
    longitude: -117.0556,
    elevations: {
      base: 4134,
      mid: 6000,
      summit: 8033,
    },
  },
  {
    id: "fernie",
    name: "Fernie Alpine Resort",
    state: "British Columbia",
    country: "Canada",
    region: "Canada",
    latitude: 49.4619,
    longitude: -115.0981,
    elevations: {
      base: 3504,
      mid: 5300,
      summit: 6325,
    },
  },
  {
    id: "tremblant",
    name: "Mont Tremblant",
    state: "Quebec",
    country: "Canada",
    region: "Canada",
    latitude: 46.21,
    longitude: -74.585,
    elevations: {
      base: 755,
      mid: 1800,
      summit: 2871,
    },
    passes: ["Ikon"],
    season: {
      openingDay: "2024-11-23",
      closingDay: "2025-04-20",
      typicalOpening: "11-20",
      typicalClosing: "04-20",
    },
  },
  {
    id: "revelstoke",
    name: "Revelstoke Mountain Resort",
    state: "British Columbia",
    country: "Canada",
    region: "Canada",
    latitude: 50.958,
    longitude: -118.165,
    elevations: {
      base: 1680,
      mid: 4500,
      summit: 7300,
    },
    passes: ["Ikon"],
    season: {
      openingDay: "2024-12-07",
      closingDay: "2025-04-20",
      typicalOpening: "12-01",
      typicalClosing: "04-20",
    },
  },
  {
    id: "niseko",
    name: "Niseko United",
    state: "Hokkaido",
    country: "Japan",
    region: "International",
    latitude: 42.8048,
    longitude: 140.6875,
    elevations: {
      base: 886,
      mid: 2625,
      summit: 4232,
    },
  },
  {
    id: "livigno",
    name: "Livigno Ski Area",
    state: "Lombardy",
    country: "Italy",
    region: "International",
    latitude: 46.5347,
    longitude: 10.1342,
    elevations: {
      base: 5869,
      mid: 7700,
      summit: 9514,
    },
  },
];

export function getResortById(id: string): Resort | undefined {
  return RESORTS.find((resort) => resort.id === id);
}
