import { Resort } from "@/types";

export const RESORTS: Resort[] = [
  {
    id: "stowe",
    name: "Stowe Mountain Resort",
    state: "Vermont",
    country: "USA",
    region: "Northeast USA",
    latitude: 44.5305,
    longitude: -72.7817,
    elevations: {
      base: 1600,
      mid: 2750,
      summit: 3625,
    },
    passes: ["Epic"],
    season: {
      openingDay: "2025-11-22",
      closingDay: "2026-04-20",
      typicalOpening: "11-20",
      typicalClosing: "04-20",
    },
    lifts: [
      { name: "Gondola", type: "Gondola", bottomElevation: 1600, topElevation: 3625, windExposure: "Moderate" },
      { name: "Fourrunner Quad", type: "High-Speed Quad", bottomElevation: 1600, topElevation: 2360, windExposure: "Low" },
      { name: "Sensation Quad", type: "High-Speed Quad", bottomElevation: 2360, topElevation: 2900, windExposure: "Moderate" },
      { name: "Sunny Spruce Quad", type: "Fixed Quad", bottomElevation: 1600, topElevation: 2100, windExposure: "Low" },
      { name: "Mansfield Triple", type: "Triple", bottomElevation: 2900, topElevation: 3625, windExposure: "High" },
      { name: "Chin Clip Quad", type: "High-Speed Quad", bottomElevation: 2900, topElevation: 3625, windExposure: "High" },
      { name: "Lookout Double", type: "Double", bottomElevation: 2100, topElevation: 2600, windExposure: "Moderate" },
      { name: "Perry Merrill Double", type: "Double", bottomElevation: 1600, topElevation: 2100, windExposure: "Low" },
    ],
    liftOpeningTime: "8:00 AM",
    parkingInstructions: "Main parking lots are located at the base of Mount Mansfield. Arrive early on weekends and holidays as parking fills quickly. Overflow parking is available with shuttle service. Consider using the Mountain Road Park & Ride with free shuttle service during peak season.",
    parkingCost: "paid",
  },
  {
    id: "mad-river-glen",
    name: "Mad River Glen",
    state: "Vermont",
    country: "USA",
    region: "Northeast USA",
    latitude: 44.2011,
    longitude: -72.9211,
    elevations: {
      base: 1600,
      mid: 2550,
      summit: 3637,
    },
    passes: ["Independent"],
    season: {
      openingDay: "2025-12-13",
      closingDay: "2026-04-06",
      typicalOpening: "12-13",
      typicalClosing: "04-06",
    },
    blogUrl: "http://madriverglenweather.blogspot.com/",
    liftOpeningTime: "9:00 AM",
    parkingInstructions: "Free parking available in gravel lot at the base. Arrive early on weekends and holidays as spaces fill quickly. Known for its single-chair lift and co-op ownership model.",
    parkingCost: "free",
  },
  {
    id: "jay-peak",
    name: "Jay Peak Resort",
    state: "Vermont",
    country: "USA",
    region: "Northeast USA",
    latitude: 44.9364,
    longitude: -72.5031,
    elevations: {
      base: 1815,
      mid: 2815,
      summit: 3968,
    },
    passes: ["Indy", "Independent"],
    season: {
      openingDay: "2025-11-28",
      closingDay: "2026-04-27",
      typicalOpening: "11-28",
      typicalClosing: "04-27",
    },
    liftOpeningTime: "9:00 AM",
    parkingInstructions: "Abundant free parking available at the base. Multiple parking lots provide easy access to the tram and lifts. Jay Peak is known for receiving the most natural snowfall in the East.",
    parkingCost: "free",
  },
  {
    id: "sugarbush",
    name: "Sugarbush Resort",
    state: "Vermont",
    country: "USA",
    region: "Northeast USA",
    latitude: 44.1347,
    longitude: -72.9028,
    elevations: {
      base: 1535,
      mid: 2700,
      summit: 4083,
    },
    passes: ["Ikon"],
    season: {
      openingDay: "2025-11-22",
      closingDay: "2026-04-20",
      typicalOpening: "11-22",
      typicalClosing: "04-20",
    },
    liftOpeningTime: "8:00 AM",
    parkingInstructions: "Free standard parking available at both Lincoln Peak and Mt. Ellen base areas. Limited valet parking available on weekends and holidays. Free GMT Bus provides transportation between mountains and throughout Mad River Valley. Green Mountain Express Quad at Mt. Ellen opens at 8 AM, while Lincoln Peak lifts open at 9 AM midweek.",
    parkingCost: "free",
  },
  {
    id: "magic-mountain",
    name: "Magic Mountain",
    state: "Vermont",
    country: "USA",
    region: "Northeast USA",
    latitude: 43.2,
    longitude: -72.77,
    elevations: {
      base: 1350,
      mid: 2100,
      summit: 2850,
    },
    passes: ["Indy", "Independent"],
    season: {
      openingDay: "2025-12-21",
      closingDay: "2026-04-06",
      typicalOpening: "12-20",
      typicalClosing: "04-06",
    },
    liftOpeningTime: "8:30 AM",
    parkingInstructions: "100% free parking in Lots A and B at the base area. Open Thursday through Sunday and all days during holiday season. Known for authentic Vermont skiing experience and community-owned operation.",
    parkingCost: "free",
  },
  {
    id: "killington",
    name: "Killington Resort",
    state: "Vermont",
    country: "USA",
    region: "Northeast USA",
    latitude: 43.6045,
    longitude: -72.8203,
    elevations: {
      base: 1165,
      mid: 2700,
      summit: 4241,
    },
    passes: ["Ikon", "Independent"],
    season: {
      openingDay: "2025-11-21",
      closingDay: "2026-05-25",
      typicalOpening: "10-20",
      typicalClosing: "05-25",
    },
    liftOpeningTime: "8:00 AM",
    parkingInstructions: "Sufficient free parking available at all base stations including K-1, Snowshed, Ramshead, and Bear Mountain. Preferred parking at K-1 and valet service at Snowshed available for a fee. Killington offers the longest ski season in the East.",
    parkingCost: "free",
  },
  {
    id: "sunday-river",
    name: "Sunday River",
    state: "Maine",
    country: "USA",
    region: "Northeast USA",
    latitude: 44.4728,
    longitude: -70.8561,
    elevations: {
      base: 800,
      mid: 2100,
      summit: 3140,
    },
    passes: ["Ikon", "Independent"],
    season: {
      openingDay: "2025-11-13",
      closingDay: "2026-04-27",
      typicalOpening: "11-13",
      typicalClosing: "04-27",
    },
    liftOpeningTime: "8:00 AM",
    parkingInstructions: "Sufficient free parking available at all base stations. Eight different peaks provide multiple parking areas for easy access. Note: lift closing times vary from 3:15-3:45 PM from late October to mid-January due to sunset.",
    parkingCost: "free",
  },
  {
    id: "sugarloaf",
    name: "Sugarloaf",
    state: "Maine",
    country: "USA",
    region: "Northeast USA",
    latitude: 45.0317,
    longitude: -70.3133,
    elevations: {
      base: 1417,
      mid: 2825,
      summit: 4237,
    },
    passes: ["Ikon", "Independent"],
    season: {
      openingDay: "2025-11-29",
      closingDay: "2026-05-04",
      typicalOpening: "11-29",
      typicalClosing: "05-04",
    },
    liftOpeningTime: "8:30 AM",
    parkingInstructions: "Free parking and shuttle services available. Hassle-free drop-offs with two dedicated lanes in the hotel lot. Overnight camping and EV charging stations available. Offers the only lift-serviced above-treeline skiing in the East.",
    parkingCost: "free",
  },
  {
    id: "mammoth",
    name: "Mammoth Mountain",
    state: "California",
    country: "USA",
    region: "Western USA",
    latitude: 37.6308,
    longitude: -119.0326,
    elevations: {
      base: 7953,
      mid: 9500,
      summit: 11053,
    },
    passes: ["Ikon"],
    season: {
      openingDay: "2025-11-14",
      closingDay: "2026-05-26",
      typicalOpening: "11-14",
      typicalClosing: "05-26",
    },
    liftOpeningTime: "8:30 AM",
    parkingInstructions: "Free parking at all Mammoth Mountain lodges, with lots opening at 6:00 AM. Preferred parking available on first-come, first-served basis. Overnight parking prohibited during winter season. Parking may be limited on weekends and holidays.",
    parkingCost: "free",
  },
  {
    id: "powder-mountain",
    name: "Powder Mountain",
    state: "Utah",
    country: "USA",
    region: "Western USA",
    latitude: 41.3803,
    longitude: -111.7797,
    elevations: {
      base: 6895,
      mid: 8200,
      summit: 8464,
    },
    passes: ["Ikon"],
    season: {
      openingDay: "2025-12-12",
      closingDay: "2026-04-13",
      typicalOpening: "12-12",
      typicalClosing: "04-13",
    },
    liftOpeningTime: "9:00 AM",
    parkingInstructions: "Free parking available at Timberline, Hidden Lake, and Sundown base areas without reservation on weekdays. Weekend parking ($12) implemented for 2025-26 season. Boasts the most skiable acres in North America with minimal crowds.",
    parkingCost: "paid_weekends",
  },
  {
    id: "taos",
    name: "Taos Ski Valley",
    state: "New Mexico",
    country: "USA",
    region: "Western USA",
    latitude: 36.5972,
    longitude: -105.4461,
    elevations: {
      base: 9207,
      mid: 10800,
      summit: 12481,
    },
    passes: ["Ikon"],
    season: {
      openingDay: "2025-11-27",
      closingDay: "2026-04-06",
      typicalOpening: "11-27",
      typicalClosing: "04-06",
    },
    liftOpeningTime: "9:00 AM",
    parkingInstructions: "Plenty of free parking available at the base. Operating hours 9 AM - 4 PM. Celebrating 70th anniversary with special $70 lift tickets through December 2025. Known for steep terrain and genuine New Mexico hospitality.",
    parkingCost: "free",
  },
  {
    id: "telluride",
    name: "Telluride Ski Resort",
    state: "Colorado",
    country: "USA",
    region: "Western USA",
    latitude: 37.9375,
    longitude: -107.8123,
    elevations: {
      base: 8725,
      mid: 10900,
      summit: 12570,
    },
    passes: ["Epic"],
    season: {
      openingDay: "2025-11-27",
      closingDay: "2026-04-05",
      typicalOpening: "11-27",
      typicalClosing: "04-05",
    },
    liftOpeningTime: "9:00 AM",
    parkingInstructions: "Free parking available at Carhenge Lot at the base of Lift 7 in Town of Telluride. Paid parking options available in Mountain Village at Gondola Parking Garage, Meadows Lot, and Heritage Parking Garage. Free gondola connects town to mountain village.",
    parkingCost: "free",
  },
  {
    id: "arapahoe-basin",
    name: "Arapahoe Basin",
    state: "Colorado",
    country: "USA",
    region: "Western USA",
    latitude: 39.6425,
    longitude: -105.8719,
    elevations: {
      base: 10780,
      mid: 11800,
      summit: 13050,
    },
    passes: ["Ikon"],
    season: {
      openingDay: "2025-10-26",
      closingDay: "2026-06-01",
      typicalOpening: "10-26",
      typicalClosing: "06-01",
    },
    liftOpeningTime: "8:30 AM",
    parkingInstructions: "Parking reservations required on weekends (Saturdays and Sundays) from January 3 to May 3 between 6 AM and 1 PM. General parking $20 per reservation, free for carpools of 4+. Season parking pass available for $229. ADA accessible parking free but requires reservation. Lifts operate 8:30 AM - 4 PM.",
    parkingCost: "paid_weekends",
  },
  {
    id: "kicking-horse",
    name: "Kicking Horse Mountain Resort",
    state: "British Columbia",
    country: "Canada",
    region: "Canada",
    latitude: 51.2989,
    longitude: -117.0556,
    elevations: {
      base: 4134,
      mid: 6000,
      summit: 8033,
    },
    season: {
      openingDay: "2025-12-05",
      closingDay: "2026-04-20",
      typicalOpening: "12-05",
      typicalClosing: "04-20",
    },
    liftOpeningTime: "9:00 AM",
    parkingInstructions: "Plenty of free parking available at the base station with both paved and gravel lots. Located near Golden, BC, known for its legendary powder and steep terrain accessed by North America's highest lift-served vertical.",
    parkingCost: "free",
  },
  {
    id: "fernie",
    name: "Fernie Alpine Resort",
    state: "British Columbia",
    country: "Canada",
    region: "Canada",
    latitude: 49.4619,
    longitude: -115.0981,
    elevations: {
      base: 3504,
      mid: 5300,
      summit: 6325,
    },
    season: {
      openingDay: "2025-12-05",
      closingDay: "2026-04-20",
      typicalOpening: "12-05",
      typicalClosing: "04-20",
    },
    liftOpeningTime: "9:00 AM",
    parkingInstructions: "Free parking available with paved and gravel lots at the base. Season pass holders can purchase priority parking passes at 20% discount to park closer to lifts. Operating hours 9 AM - 4 PM MST. Famous for champagne powder and legendary snow ghosts.",
    parkingCost: "free",
  },
  {
    id: "tremblant",
    name: "Mont Tremblant",
    state: "Quebec",
    country: "Canada",
    region: "Canada",
    latitude: 46.21,
    longitude: -74.585,
    elevations: {
      base: 755,
      mid: 1800,
      summit: 2871,
    },
    passes: ["Ikon"],
    season: {
      openingDay: "2025-11-27",
      closingDay: "2026-04-20",
      typicalOpening: "11-27",
      typicalClosing: "04-20",
    },
    liftOpeningTime: "8:30 AM",
    parkingInstructions: "Free parking available in outer lots and on north side of resort. Paid parking available at village hotels and closer lots. European-style pedestrian village at the base provides ski-in/ski-out access. Quebec's premier four-season resort.",
    parkingCost: "free",
  },
  {
    id: "revelstoke",
    name: "Revelstoke Mountain Resort",
    state: "British Columbia",
    country: "Canada",
    region: "Canada",
    latitude: 50.958,
    longitude: -118.165,
    elevations: {
      base: 1680,
      mid: 4500,
      summit: 7300,
    },
    passes: ["Ikon"],
    season: {
      openingDay: "2025-11-29",
      closingDay: "2026-04-20",
      typicalOpening: "11-29",
      typicalClosing: "04-20",
    },
    liftOpeningTime: "8:30 AM",
    parkingInstructions: "Plenty of free parking at the base station. Resort located about 6 km from the town of Revelstoke. Offers North America's longest lift-served vertical at 5,620 feet and legendary tree skiing in the Selkirk Mountains.",
    parkingCost: "free",
  },
  {
    id: "banff-sunshine",
    name: "Banff Sunshine Village",
    state: "Alberta",
    country: "Canada",
    region: "Canada",
    latitude: 51.1147,
    longitude: -115.7630,
    elevations: {
      base: 5440,
      mid: 7000,
      summit: 8954,
    },
    passes: ["Ikon"],
    season: {
      openingDay: "2025-11-02",
      closingDay: "2026-05-18",
      typicalOpening: "11-08",
      typicalClosing: "05-18",
    },
    lifts: [
      { name: "Sunshine Gondola", type: "Gondola", bottomElevation: 5440, topElevation: 7200, windExposure: "Low" },
      { name: "Teepee Town LX", type: "High-Speed Quad", bottomElevation: 7090, topElevation: 8300, windExposure: "Moderate" },
      { name: "Goat's Eye Express", type: "High-Speed Quad", bottomElevation: 7200, topElevation: 8900, windExposure: "High" },
      { name: "Standish Chairlift", type: "High-Speed Quad", bottomElevation: 7090, topElevation: 8960, windExposure: "High" },
      { name: "Angel Express", type: "High-Speed Quad", bottomElevation: 7090, topElevation: 8200, windExposure: "Moderate" },
      { name: "Wolverine Express", type: "High-Speed Quad", bottomElevation: 7090, topElevation: 8100, windExposure: "Moderate" },
    ],
    liftOpeningTime: "8:00 AM",
    parkingInstructions: "Free parking at the base area with easy access to the gondola terminal. Free shuttle buses available from the Town of Banff with pickup at several hotels and Brewster's Depot. Located 8km west of Banff.",
    parkingCost: "free",
  },
  {
    id: "niseko",
    name: "Niseko United",
    state: "Hokkaido",
    country: "Japan",
    region: "International",
    latitude: 42.8048,
    longitude: 140.6875,
    elevations: {
      base: 886,
      mid: 2625,
      summit: 4232,
    },
  },
  {
    id: "livigno",
    name: "Livigno Ski Area",
    state: "Lombardy",
    country: "Italy",
    region: "International",
    latitude: 46.5347,
    longitude: 10.1342,
    elevations: {
      base: 5869,
      mid: 7700,
      summit: 9514,
    },
  },
];

export function getResortById(id: string): Resort | undefined {
  return RESORTS.find((resort) => resort.id === id);
}
